// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourTask.Infrastructure;

#nullable disable

namespace YourTask.Infrastructure.Migrations
{
    [DbContext(typeof(YourTaskContext))]
    [Migration("20250311021059_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YourTask.Domain.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusTarefa")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tarefas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataConclusao = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Comprar frutas, vegetais e laticínios.",
                            StatusTarefa = 2,
                            Titulo = "Comprar mantimentos"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Reunião com a equipe de marketing.",
                            StatusTarefa = 1,
                            Titulo = "Agendar reunião"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Revisar conceitos de layout e binding.",
                            StatusTarefa = 0,
                            Titulo = "Estudar WPF"
                        },
                        new
                        {
                            Id = 4,
                            DataConclusao = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Enviar relatórios semanais.",
                            StatusTarefa = 2,
                            Titulo = "Enviar e-mails"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Incluir os projetos recentes.",
                            StatusTarefa = 1,
                            Titulo = "Atualizar portfólio"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pesquisar destinos e reservar passagens.",
                            StatusTarefa = 0,
                            Titulo = "Planejar viagem"
                        },
                        new
                        {
                            Id = 7,
                            DataConclusao = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Terminar leitura do best-seller.",
                            StatusTarefa = 2,
                            Titulo = "Ler livro"
                        },
                        new
                        {
                            Id = 8,
                            DataCriacao = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sessão de feedback com a equipe de desenvolvimento.",
                            StatusTarefa = 1,
                            Titulo = "Reunião de feedback"
                        },
                        new
                        {
                            Id = 9,
                            DataConclusao = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Limpeza completa no escritório.",
                            StatusTarefa = 2,
                            Titulo = "Limpeza geral"
                        },
                        new
                        {
                            Id = 10,
                            DataCriacao = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Criar um protótipo funcional.",
                            StatusTarefa = 0,
                            Titulo = "Desenvolver protótipo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
