services:
  api:
    image: yourtask-api
    build:
      context: .
      dockerfile: YourTask.Presentation/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=YourTaskDB;User Id=sa;Password=1234Abc!@#;TrustServerCertificate=true;
    depends_on:
      - sqlserver

  migrations:
    image: yourtask-migrations
    build:
      context: .
      dockerfile: YourTask.Presentation/Dockerfile.migrations
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=YourTaskDB;User Id=sa;Password=1234Abc!@#;TrustServerCertificate=true;
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: 1234Abc!@#
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 1234Abc!@# -C -Q 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  sqlserver_data:
